<div class="content">
    <?php View::content() ?>
    <?php
    Tag::css('empresa');     //Pone en lista un CSS (app/public/css/bienvenida.css)
    echo Html::includeCss();   //Adiciona los recursos enlazados de la clase en el proyecto  

    ?>
    <h4>Inscripcion Nro: <strong><?php echo $nro_inscripcion; ?></strong>
    </h4>

    <table style="text-align: center;">
        <th>ID</th>
        <th>Nombre</th>
        <th>Instructor</th>
        <th colspan="1">Acciones</th>

        <?php foreach ($listClaseInscripcion as $claseInscripcion) : ?>
            <tr>
                <td><strong><?= $claseInscripcion->id ?> </strong> </td>
                <td><strong><?= $claseInscripcion->nombre ?> </strong> </td>
                <td><strong><?= $claseInscripcion->instructor ?> </strong> </td>
                <td><?= Html::linkAction("baja/$claseInscripcion->nro_inscripcion/", 'Borrar') ?></td>
            </tr>
        <?php endforeach ?>
    </table>

</div>