<div class="content">

    <?php View::content() ?>
    <?php
    Tag::css('empresa');     //Pone en lista un CSS (app/public/css/bienvenida.css)
    echo  Html::includeCss();   //Adiciona los recursos enlazados de la clase en el proyecto  
    ?>
    <div class="barraCategoria">
        <h3 class="tituloCategoria">Socios/Miembros</h3>
        <i class="fa fa-plus-circle icono-categoria" aria-hidden="true"><?= Html::linkAction("alta/", ' Nuevo') ?></i>
    </div>

    <table style="text-align: center;  border: 1px solid black;  border-collapse: collapse;">
        <th>ID</th>
        <th>Nombre, Apellido</th>
        <th>DNI</th>
        <th>Fecha de Nacimiento</th>
        <th>Fecha Inscripción</th>
        <th>Tipo membresía</th>
        <th colspan="2">Acciones</th>
        <th colspan="3">Clases</th>

        <?php foreach ($listSocio->items as $socio) : ?>

            <tr>
                <td><strong><?= $socio->id ?> </strong> </td>
                <td><strong><?= $socio->nombre ?> , <?= $socio->apellido ?></strong> </td>
                <td><strong><?= $socio->dni ?></strong   > </td>
                <td><strong><?= $socio->fechaNacimiento ?></strong> </td>
                <td><strong><?= $socio->fechaInscripcion ?></strong> </td>
                <td><strong><?= $socio->tipoMembresia ?></strong> </td>
                <td><?= Html::linkAction("modif/$socio->id/", 'Editar') ?></td>
                <td><?= Html::linkAction("baja/$socio->id/", 'Borrar') ?></td>
                <td><?= Html::linkAction("../inscripcion/getInscripcionSocio/$socio->id/", 'Inscripciones') ?></td>
                <td><?= Html::linkAction("../inscripcion/nuevaInscripcion/$socio->id/", 'Nueva Inscripcion') ?></td>
                <td><?= Html::linkAction("../asistencia/consultarAsistencia/", 'Asistencias') ?></td>
            </tr>
        <?php endforeach ?>
    </table>

</div>